spring.application.name=secret-api


pring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

# Mantenha as credenciais
spring.datasource.username=${DB_USER}
spring.datasource.password=${DATABASE_PASSWORD}

# ⚠️ O Driver e o Dialeto SÃO CRUCIAIS PARA O HIBERNATE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Certifique-se de que ddl-auto está definido para 'none'
spring.jpa.hibernate.ddl-auto=none
