spring.application.name=secret-api

# ----------------------------------------------------
# 1. CONFIGURAÇÕES DE CONEXÃO DO BANCO DE DADOS (RENDER)
# ----------------------------------------------------
# O Render injetará estes valores do ambiente
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ----------------------------------------------------
# 2. CONFIGURAÇÕES DO HIBERNATE (JPA)
# ----------------------------------------------------
# Diz ao Hibernate para usar o dialeto do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CRUCIAL: O Hibernate irá verificar e atualizar as tabelas com base nas Entidades
spring.jpa.hibernate.ddl-auto=update